src/app.html, src/ng/chat/chat-options.directive.css, src/ng/chat/chat-options.directive.html, src/ng/chat/chat-options.directive.js, src/ng/providers/irc.js, src/ng/providers/messages.provider.js, src/ng/providers/settings.js
=> Added feature to ignore messages from users.

src/tc-renderer/lib/settings/default-settings.js, src/tc-renderer/lib/settings/validate-settings.js, src/tc-renderer/ng/elements/chat-output/chat-output.css, src/tc-renderer/ng/elements/chat-output/chat-output.html, src/tc-renderer/ng/elements/chat-output/chat-output.js, src/tc-renderer/ng/elements/settings-panel/settings-panel.html
=> Variable line height

package.json, src/package.json, src/tc-renderer/lib/auto-updater.js, src/tc-renderer/lib/channels.js, src/tc-renderer/lib/settings/settings.js, src/tc-renderer/lib/startup/app-zoom.js
=> Upgrade electron to 1.4.2 from 0.37.x

src/tc-renderer/ng/providers/messages.js
=> Use message IDs to prevent duplicates from the backlog

src/tc-renderer/ng/elements/chatters/chatters.html
I saw this issue was open in the tracker and said ready, but wasn't available yet, not sure if this would be the best way to manage it but its quick and simple
=> Ability to filter through current viewers

src/tc-renderer/ng/providers/notifications.js
Add TC icon to notification
Make standard windows alert sound silent so TC notif sound is the only sound that plays on an notification
Will solve Issue #232
=> Add TC icon to notification alert

.gitignore, src/tc-renderer/ng/elements/chat-input/chat-input.html, src/tc-renderer/ng/elements/chat-input/chat-input.js
Pressing Up/Down will filter through chat history
Closes #70
=> Input History integration

src/tc-main/main.js
To cut down on conditionals I did a switch for ya lol
=> Modify the closing structure to allow linux to quit on close

src/tc-renderer/ng/elements/login/login.html, src/tc-renderer/ng/providers/irc.js, src/tc-renderer/ng/providers/messages.js
Previously, it would only show "Disconnected from server" but we actually have more info than that.
Now it also boots the user back to the login screen when appropriate.
=> Show reason for disconnection to user

src/tc-renderer/lib/chatters.js, src/tc-renderer/ng/elements/chat-input/chat-input.js, src/tc-renderer/ng/elements/chatters/chatters.js
... Instead of building the list from active chatters
=> Autocomplete from chatters list

src/tc-renderer/lib/chatters.js, src/tc-renderer/ng/elements/chat-input/chat-input.js, src/tc-renderer/ng/elements/chatters/chatters.js
- Use viewer list (from API)
- Use active chatters (even if they're not in the viewer list)
- Use display names, if available
- Clear old display names cache to prevent memory leaking
See: https://github.com/mccxiv/tc/issues/341
=> Better username autocompletion

src/tc-renderer/lib/emotes/bttv.js, src/tc-renderer/lib/emotes/ffz.js, src/tc-renderer/lib/emotes/menu.js, src/tc-renderer/lib/startup/angular-stuff.js, src/tc-renderer/ng/elements/chat-input/chat-input.css, src/tc-renderer/ng/elements/chat-input/chat-input.html, src/tc-renderer/ng/elements/chat-input/chat-input.js, src/tc-renderer/ng/elements/emote-menu/emote-menu.css, src/tc-renderer/ng/elements/emote-menu/emote-menu.html, src/tc-renderer/ng/elements/emote-menu/emote-menu.js, src/tc-renderer/ng/providers/emotes-twitch.js, src/tc-renderer/renderer.js
=> Emote menu

src/package-lock.json, src/package.json, src/tc-renderer/lib/emotes/twitch.js
JS doesn't handle emojis well, let's use a library instead
=> Fix emotes following emojis

src/tc-renderer/ng/elements/thumbnail/thumbnail.js, src/tc-renderer/ng/providers/irc.js, src/tc-renderer/ng/providers/messages.js
Users weren't booted to the login screen as intended
=> 171118 fix bad login

src/tc-renderer/lib/api.js, src/tc-renderer/lib/util.js
=> Fix bit badges

package.json, src/package-lock.json, src/tc-main/lib/squirrel-startup.js, src/tc-main/main.js, src/tc-renderer/lib/auto-updater.js, src/tc-renderer/lib/chatters.js, src/tc-renderer/lib/colors.js, src/tc-renderer/lib/emotes/bttv.js, src/tc-renderer/lib/emotes/ffz.js, src/tc-renderer/lib/settings/settings.js, src/tc-renderer/lib/settings/validate-settings.js, src/tc-renderer/lib/startup/enable-menu-on-mac.js, src/tc-renderer/lib/startup/icon-font.js, src/tc-renderer/lib/startup/keep-title-updated.js, src/tc-renderer/lib/transforms/add-links.js, src/tc-renderer/ng/elements/add-channel/add-channel.js, src/tc-renderer/ng/elements/chat-input/chat-input.js, src/tc-renderer/ng/elements/chat-output/chat-output.js, src/tc-renderer/ng/elements/chat-tabs/chat-tabs.js, src/tc-renderer/ng/elements/chatters/chatters.js, src/tc-renderer/ng/elements/settings-panel/settings-panel.js, src/tc-renderer/ng/elements/side-toolbar/side-toolbar.js, src/tc-renderer/ng/providers/emotes-twitch.js, src/tc-renderer/ng/providers/highlights.js, src/tc-renderer/ng/providers/irc.js, src/tc-renderer/ng/providers/manifest.js, src/tc-renderer/ng/providers/messages.js, src/tc-renderer/ng/providers/notifications.js, src/tc-renderer/ng/providers/session.js
There's still some work to do, I want to add husky + linting on pre-commit hook
=> ESlint + Standard

src/tc-main/main.js, src/tc-renderer/lib/startup/commandline.js, src/tc-renderer/ng/elements/add-channel/add-channel.js, src/tc-renderer/renderer.js
Cross OS command line functionality to join channels
=> command line argument to join channel

src/package-lock.json, src/package.json, src/tc-renderer/ng/providers/irc.js, src/tc-renderer/ng/providers/messages.js, webpack.config.js
Most of the work of this PR actually went into `twitch-js`, this branch: https://github.com/mccxiv/twitch-js/tree/180324-emit-all-notice
I'll try it out for a few days and if it's all good I'll send in a PR to their repo
=> Switch to twitch-js (But still a forked version)

gulpfile.js, webpack.config.js
This adds a check on what platform you're trying to build Tc on and act accordingly.
Someone however needs to inform me on what Mac is capable of building! So don't merge until that's been done. Currently Mac contains all 3 builds.
Also added some options in webpack's config to surpress some console clutter, I'm not sure if this'll hide critical information though.
Closes #407
=> Improve building process

package-lock.json, src/package-lock.json, src/package.json, src/tc-renderer/lib/emotes/twitch.js, src/tc-renderer/lib/transforms/process-message.js
fixes #411, and also the missing regex emotes like `:-)` in outgoing messages
=> Fix outgoing emotes

src/tc-renderer/ng/elements/add-channel/add-channel.js, src/tc-renderer/ng/elements/chat-input/chat-input.js, src/tc-renderer/ng/elements/chat-tabs/chat-tabs.js, src/tc-renderer/ng/elements/chatters-tabs/chatters-tabs.js, src/tc-renderer/ng/elements/emote-menu/emote-menu.js, src/tc-renderer/ng/elements/login/login.js, src/tc-renderer/ng/elements/settings-panel/settings-panel.js, src/tc-renderer/ng/elements/side-toolbar/side-toolbar.js, src/tc-renderer/ng/elements/thumbnail/thumbnail.js, src/tc-renderer/ng/elements/user-panel/user-panel.js
=> Isolate directive scopes

docs/password/index.html
=> Make it easier to copy the oauth code correctly

src/tc-renderer/lib/emotes/menu.js, src/tc-renderer/ng/providers/emotes-twitch.js
Hopefully this means your emotes (autocomplete and emote menu) will update when you sub to a new channel or a sub runs out.
But it's hard to test because it costs money 👀
=> Listen to the emotesets event more than once

src/tc-renderer/ng/components/add-channel/add-channel.js, src/tc-renderer/ng/components/chat-output/chat-output.js, src/tc-renderer/ng/components/chat-tabs/chat-tabs.js, src/tc-renderer/ng/components/chatters-tabs/chatters-tabs.js, src/tc-renderer/ng/components/chatters-tabs/chatters-tabs.pug, src/tc-renderer/ng/components/chatters/chatters.js, src/tc-renderer/ng/components/chatters/chatters.pug, src/tc-renderer/ng/components/side-toolbar/side-toolbar.js, src/tc-renderer/ng/components/thumbnail/thumbnail.js, src/tc-renderer/ng/components/user-panel/user-panel.js, src/tc-renderer/ng/providers/messages.js
=> Fix console errors

src/tc-renderer/ng/components/chat-tabs/chat-tabs.js
=> Fix message count not updating

src/package-lock.json, src/package.json, src/tc-renderer/ng/components/chat-output/chat-output.js
Super unfortunate that I'm maintaining my own branch. I should really switch back to the main repo but the changes are too scary
=> Fix isMod which is buggy in twitch-js

src/tc-renderer/store/modules/settings/validate-settings.js
=> Fix shortcuts

src/tc-renderer/ng/components/user-panel/user-panel.js, src/tc-renderer/ng/components/user-panel/user-panel.pug
=> Fix user info display when selecting a user
